---
title: "Module 4 Pair Quiz"
author: Gian Carlo Fernandez, Iris Salangad
output: 
  html_document:
    highlight: pygments
    theme: darkly
---

# Individual Quiz {.tabset}

## Q1

### An article in the Journal of Sound and Vibration *[“Measurement of Noise-Evoked Blood Pressure by Means of Averaging Method: Relation between Blood Pressure Rise and PSL” (1991, Vol. 151(3), pp. 383-394)]* described a study investigating the relationship between noise exposure and hypertension. The following data are representative of those reported in the article.

-------------------------------------------------------------------------------------

<table style="width:100%"; border = 1px>
  <tr>
    <th>y</th>
    <th>1</th>
    <th>0</th>
    <th>1</th>
    <th>2</th>
    <th>5</th>
    <th>1</th>
    <th>4</th>
    <th>6</th>
    <th>2</th>
    <th>3</th>
    <th>5</th>
    <th>4</th>
    <th>6</th>
    <th>8</th>
    <th>4</th>
    <th>5</th>
    <th>7</th>
    <th>9</th>
    <th>7</th>
    <th>6</th>
  </tr>
 <tr>
    <th>x</th>
    <th>60</th>
    <th>63</th>
    <th>65</th>
    <th>70</th>
    <th>70</th>
    <th>70</th>
    <th>80</th>
    <th>90</th>
    <th>80</th>
    <th>80</th>
    <th>85</th>
    <th>89</th>
    <th>90</th>
    <th>90</th>
    <th>90</th>
    <th>90</th>
    <th>94</th>
    <th>100</th>
    <th>100</th>
    <th>100</th>
  </tr>
</table>

-------------------------------------------------------------------------------------

#### A. Draw a scatter diagram of y (blood pressure rise in millimeters of mercury) versus x (sound pressure level in decibels). Does a simple linear regression seem reasonable in this situation? 

```{r}
y <- c(1, 0, 1, 2, 5, 1, 4, 6, 2, 3, 5, 4, 6, 8, 4, 5, 7, 9, 7, 6)

x <- c(60, 63, 65, 70, 70, 70, 80, 90, 80, 80, 85, 89, 90, 90, 90, 90, 94, 100, 100, 100)

plot(x,y, pch = 16, cex = 1, col = "dark green", main = "Sound Pressure Level vs Blood Pressure Rise", xlab = "Sound Pressure Levels (in decibels)", ylab = "Blood Pressure Rise (in mmHg)")

abline(lm(y ~ x))
```
Graph 1. A Scatter Plot between **x** (*Sound Pressure Levels*) and **y** (*Blood Pressure Rise*)



#### B. Fit the simple linear regression model using least squares. Find an estimate of $\sigma^2$.

#### C. Find the predicted mean rise in blood pressure level associated with a sound pressure level of 85 decibels.

## Q2

-------------------------------------------------------------------------------------

### An article in the Journal of Sound and Vibration *[“Measurement of Noise-Evoked Blood Pressure by Means of Averaging Method: Relation between Blood Pressure Rise and PSL” (1991, Vol. 151(3), pp. 383-394)]* described a study investigating the relationship between noise exposure and hypertension. The following data are representative of those reported in the article.

------

<table style="width:100%"; border: 5px>
  <tr>
    <th>Brightness (%) </th>
    <th>54</th>
    <th>61</th>
    <th>65</th>
    <th>100</th>
    <th>100</th>
    <th>100</th>
    <th>50</th>
    <th>57</th>
    <th>54</th>
  </tr>
 <tr>
    <th>Contrast (%) </th>
    <th>56</th>
    <th>80</th>
    <th>70</th>
    <th>50</th>
    <th>65</th>
    <th>80</th>
    <th>25</th>
    <th>35</th>
    <th>26</th>
  </tr>
<tr>
    <th>Useful Range (ng) </th>
    <th>96</th>
    <th>50</th>
    <th>50</th>
    <th>112</th>
    <th>96</th>
    <th>80</th>
    <th>155</th>
    <th>144</th>
    <th>255</th>
</table>
